// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import { MiddleSayCoucouPanel } from "@/wab/client/components/sidebar-contents/MiddleSayCoucouPanel";
import { LeftTabKey } from "@/wab/shared/ui-config-utils";
import React from "react";

interface MiddleContentsProps {
  leftTabKey?: LeftTabKey;
}

export function MiddlePane(props: MiddleContentsProps) {
  const { leftTabKey } = props;

  const wrapContent = (
    tabKey: LeftTabKey,
    panel: React.ReactNode,
    unmount = false
  ) => {
    return (
      (!unmount || leftTabKey === tabKey) && (
        <div
          className="flex-col flex-fill overflow-hidden"
          style={
            tabKey === leftTabKey
              ? {
                  display: "flex",
                  justifyContent: "center",
                  alignItems: "center",
                  width: "100%",
                  height: "100%",
                  padding: 20,
                  backgroundColor: "#F9F9F8",
                  pointerEvents: "all",
                }
              : { display: "none" }
          }
        >
          {panel}
        </div>
      )
    );
  };

  return (
    <div
      style={{
        width: "100%",
        height: "100%",
        position: "absolute",
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        zIndex: 10,
        pointerEvents: "none",
      }}
    >
      {wrapContent("sayCoucouPanelMiddle", <MiddleSayCoucouPanel />)}
      {wrapContent("sayCoucouMiddle", <MiddleSayCoucouPanel />)}
    </div>
  );
}
