// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import LeftPaneHeader from "@/wab/client/components/studio/LeftPaneHeader";
import Button from "@/wab/client/components/widgets/Button";
import SpeakersvgIcon from "@/wab/client/plasmic/q_4_icons/icons/PlasmicIcon__Speakersvg";
import React from "react";

function handleClick() {
  alert("Coucou");
}

export function LeftSayCoucouPanel(props: {}) {
  return (
    <div>
      <LeftPaneHeader
        actions={
          <Button
            size={"wide"}
            startIcon={<SpeakersvgIcon />}
            type={["secondary"]}
            withIcons={["startIcon"]}
            onClick={handleClick}
          >
            {"Say coucou"}
          </Button>
        }
        description={"Ich bin ein tecste."}
        hasTitleActions={true}
        title={"Teitel"}
      />
    </div>
  );
}
