// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import Button from "@/wab/client/components/widgets/Button";
import SpeakersvgIcon from "@/wab/client/plasmic/q_4_icons/icons/PlasmicIcon__Speakersvg";
import React from "react";

function handleClick() {
  alert("Coucou");
}

export function MiddleSayCoucouPanel(props: {}) {
  return (
    <div>
      <Button
        size={"wide"}
        startIcon={<SpeakersvgIcon />}
        type={["secondary"]}
        withIcons={["startIcon"]}
        onClick={handleClick}
      >
        {"Say coucou"}
      </Button>
    </div>
  );
}
